#!/usr/bin/env ruby
require 'optparse'

HELP=<<-HELP

    git ams --[environment] [branch_name] # set the name of the development branch
    git ams                  # checks out development branch and pulls any updates

HELP

ENVS = [:development, :production]

def help()
	puts HELP
end

def checkout(branch, opts="")
	if branch && branch != ""
		`git checkout#{" " + opts} #{branch}`
	else
		puts "Branch not set"
	end
end

def pull
	`git pull`
end

def switch_to(env)
	if clean?
		branch = branch_name env
		if branch != ""
			checkout branch
		else
			puts <<-INSTRUCT
	You need set your branch name for #{env} using:
			git ams --[environment] [branch]
	INSTRUCT
		end
		true
	else
		puts "\e[0;31mYou have uncommited changes.\e[m Please stash, commit or 'git reset --hard' (dangerous) first"
	end
end

def dirty?
	state = "#{`[[ $(git status 2> /dev/null | tail -n1) != 'nothing to commit (working directory clean)' ]] && echo 'dirty'`}"
	state.match(/dirty/) ? true : false
end

def clean?
	!dirty?
end

def branch_name(env)
  `git config --get workflow.#{env}`
end

def list()
	listing = []
	ENVS.each do |env|
		listing << "#{env} : #{branch_name(env)}"
	end
	puts "\nEnvironments\n============"
	puts listing
	puts ""
end

options = OptionParser.new do |opts|
  # Help
	opts.on("-h", "Get Help") do |opt|
		help
	end

  # Switching environment
	ENVS.each do |env|
		opts.on("--#{env} branch", "set branch for #{env} work") do |branch|
			`git config workflow.#{env} #{branch}`
			puts "set #{env} branch to #{branch}"
		end
	end

  # List environments
	opts.on("-ls", "--list", "show working branches") do |listing|
		list
	end
end 

def parse_args(args)
	if args
		case args.shift
		when /dev/
			pull if switch_to(:development)
		when /pro/
			pull if switch_to(:production)
		when /feature/
			if args.first
				if switch_to(:development)
					pull
					checkout(args.first, "-b")
				end
			end
		when /new/
			if args.first
				switch_to(:development)
				pull
				checkout(args.first, "-b")
			end
		when /update/
			ENVS.each do |env|
				switch_to env
				pull
			end
		when /status/
			if dirty?
				puts `git status`
			else
				puts "\e[0;32mClean Slate\e[m"
			end
		else
			list
		end
	end
end

begin
	options.parse!(ARGV)
	parse_args(ARGV)
rescue
  puts HELP
end
